version: "3"

networks:
  zeebe_network:
    driver: bridge

services:
  zeebe:
    container_name: zeebe_broker
    image: camunda/zeebe
    environment:
      - ZEEBE_LOG_LEVEL=debug
      - io.zeebe.monitor.ZeebeSimpleMonitorApp
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - ../target/exporter/zeebe-hazelcast-exporter.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - zeebe_network

  simple-monitor-in-memory:
    container_name: zeebe-simple-monitor-in-memory
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
    profiles:
      - in-memory

  simple-monitor-postgres:
    container_name: zeebe-simple-monitor-postgres
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:postgresql://postgres:5432/postgres
      - spring.datasource.username=postgres
      - spring.datasource.password=zeebe
      - spring.datasource.driverClassName=org.postgresql.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
      - postgres
    networks:
      - zeebe_network
    profiles:
      - postgres

  postgres:
    image: postgres:12.2
    restart: always
    environment:
      POSTGRES_PASSWORD: zeebe
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - zeebe_network
    profiles:
      - postgres


  simple-monitor-mysql8:
    container_name: zeebe-simple-monitor-mysql8
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.3.0
    environment:
      - zeebe.client.broker.gateway-address=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
      - spring.datasource.url=jdbc:mysql://ww-F57.local:3307/zeebe_test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&nullCatalogMeansCurrent=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      - spring.datasource.username=root
      - spring.datasource.password=123456
      - spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - zeebe_network
    profiles:
      - mysql8

  zeebe-script-worker:
    container_name: zeebe-script-worker
    image: ghcr.io/camunda-community-hub/zeebe-script-worker:1.0.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  zeebe-http-worker:
    container_name: zeebe-http-worker
    image: ghcr.io/camunda-community-hub/zeebe-http-worker:1.0.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
    depends_on:
      - zeebe
    networks:
      - zeebe_network

  zeebe-dmn-worker:
    container_name: zeebe-dmn-worker
    image: ghcr.io/camunda-community-hub/zeebe-dmn-worker:1.2.0
    environment:
      - zeebe.client.broker.gatewayAddress=zeebe:26500
      - zeebe.client.worker.dmn.repository=/usr/share/zeebe/dmn-repo
    volumes:
      - ./dmn-repo:/usr/share/zeebe/dmn-repo
    depends_on:
      - zeebe
    networks:
      - zeebe_network

volumes:
  postgres-data:
    driver: local